
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: reliable-helper-system
  rules:
    - apiGroups: [ "*" ]
      resources:
        - "*"
      verbs: [ "*" ]
    - nonResourceURLs: [ "*" ]
      verbs: [ "*" ]
